# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: AwesomeAg's blog
subtitle: hehe 
author: AwesomeAg
language: english
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.awesomeag.tk    # Note: don't forget to modify the CNAME file to your url
root: /
#permalink: :year/:month/:day/:title/
permalink: :category/:title/
permalink_defaults:
  lang: en

#Custom Setting Start

# Site settings
SEOTitle: "AwesomeAg's Blog"
email: awesomeag61@gmail.com
description: "AwesomeAg's blog hehe"
keyword: "hehe"
header-img: /img/header_img/home.jpg
article-img: /img/article_header/article_bg.jpg
404-img: /img/header_img/404.png
signature: false #show signature
signature-img: img/signature/BeanTechSign-white.png 


# SNS settings
# RSS: false
github_username:    AwesomeAg1234
# twitter_username:   
# facebook_username:  
# linkedin_username:  

# Build settings
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Duoshuo settings
# duoshuo_username: Kakashi
# Share component is depend on Comment so we can NOT use share only.
#duoshuo_share: true                     # set to false if you want to use Comment without Sharing

# Google Analytics settings
ga_track_id: 'UA-XXXXXXXX-X'          # Format: UA-xxxxxx-xx
ga_domain: yoursite

# Sidebar settings
# Copy your avatar image to `<root>/img/`:
sidebar: true                       # whether or not using Sidebar.
sidebar-about-description: "A coder and gamer hehe"
sidebar-avatar: /img/avatar/ironman.png      # use absolute URL, seeing it's used in both `/` and `/about/`
# here are the widgets you can use
widgets:
- featured-tags
- short-about
- recent-posts
- friends-blog
- archive
#- category

# widget behavior
## Archive
archives-img: /img/header_img/archives-widget.jpg
archive_type: 'monthly'
show_count: true

## Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value

## Friends
friends: [
    {
        title: "AwesomeAg",
        href: "https://blog.awesomeag.tk"
    }
]


#Custom Setting End

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: article
category_map:
  Docker: docker
  Kubernetes: kubernetes
  Golang: golang
  Nginx: nginx
  Etcd: etcd
  Database: database

tag_map:
home_posts_tag: true # show posts tags

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MM-DD-YYYY
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: archives

archive_generator:
  per_page: 10
  yearly: true
  monthly: true
  daily: false
  
# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  
# Extensions
## Plugins: https://hexo.io/plugins/

# recommended-posts
# reference: https://github.com/huiwang/hexo-recommended-posts
# recommended_posts:
#   server: https://api.he.he
#   timeoutInMillis: 10000 
#   internalLinks: 3
#   externalLinks: 0
#   autoDisplay: true,
#   titleHtml: <h2><span style="font-size:0.45em; color:gray"></span></h2>

# hexo-tag-aplayer
# reference: https://github.com/MoePlayer/hexo-tag-aplayer
# aplayer:
#   meting: true

# MeingJS support for Aplayer
# reference: https://github.com/metowolf/MetingJS & https://github.com/MoePlayer/APlayer
metingjs: false
data-id: 2423410161
data-server: netease  
data-type: playlist
data-fixed: true
  # data-mini:
  # data-autoplay:    

# Reward
reward: false
reward_comment: hehehe
wechatpay: wechatpay_url
alipay: alipay_url

# Share
# Reference: https://github.com/overtrue/share.js
share: true

# Reference: https://github.com/YuyingWu/hexo-generator-index-plus
index_generator_plus:
  path: ''
  per_page: 10

## Themes: https://hexo.io/themes/
theme: huweihuang

#sitemap
sitemap:
  path: sitemap.xml

# Deployment
# Docs: https://hexo.io/docs/deployment.html
# repository: https://github.com/hehe/hehe.github.io.git
# branch: master
#deploy:
#  type: git
#  repository: https://github.com/hehe/hehe
#  branch: gh-pages
#  message: Update CNAME
